[tools]
rojo = { source = "rojo-rbx/rojo", version = "7.0.0" }
selene = { source = "Kampfkarren/selene", version = "0.26.1" }
stylua = { source = "JohnnyMorganz/StyLua", version = "0.19.1" }
wally = { source = "UpliftGames/wally", version = "0.3.2" }
wally-package-types = { source = "JohnnyMorganz/wally-package-types", version = "1.2.1" }