[tools]
luau-lsp = { source = "JohnnyMorganz/luau-lsp", version = "1.26.0" }
rojo = { source = "rojo-rbx/rojo", version = "7.4.1" }
run-in-roblox = { source = "rojo-rbx/run-in-roblox", version = "0.3.0" }
selene = { source = "Kampfkarren/selene", version = "0.26.1" }
stylua = { source = "JohnnyMorganz/StyLua", version = "0.20.0" }
wally = { source = "UpliftGames/wally", version = "0.3.2" }
wally-package-types = { source = "JohnnyMorganz/wally-package-types", version = "1.2.1" }