[package]
name = "flipbook-labs/csf"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[place]
shared-packages = "game.ReplicatedStorage.Packages"

[dependencies]
LuauPolyfill = "jsdotlua/luau-polyfill@1.2.6"
RegExp = "jsdotlua/luau-regexp@0.2.1"

[dev-dependencies]
Jest = "jsdotlua/jest@3.4.1"
JestGlobals = "jsdotlua/jest-globals@3.4.1"